// epic_energy_front/pages/login.vue
<template>
    <div class="flex min-h-screen items-center justify-center bg-gray-100">
      <div class="w-full max-w-sm bg-white p-6 rounded shadow">
        <h1 class="text-2xl mb-4 font-bold text-center">Login</h1>
        <form @submit.prevent="onLogin">
          <div class="mb-4">
            <label class="block text-gray-700">Username</label>
            <input
              v-model="form.username"
              type="text"
              class="border rounded w-full px-3 py-2"
              required
            />
          </div>
          <div class="mb-4">
            <label class="block text-gray-700">Password</label>
            <input
              v-model="form.password"
              type="password"
              class="border rounded w-full px-3 py-2"
              required
            />
          </div>
          <button
            type="submit"
            class="bg-blue-500 w-full text-white font-semibold px-4 py-2 rounded hover:bg-blue-600"
          >
            Login
          </button>
          <p class="mt-4">
            Don't have an account?
            <NuxtLink to="/signup" class="text-blue-500 hover:text-blue-600">Sign Up</NuxtLink>
          </p>
        </form>
      </div>
    </div>
  </template>
  
  <script setup lang="ts">
  import { ref } from 'vue'
  import { useRouter } from 'vue-router'
  import { useAuth } from '~/composables/useAuth'
  
  const router = useRouter()
  const { login } = useAuth()
  
  const form = ref({
    username: '',
    password: ''
  })
  
  const onLogin = async () => {
    try {
      await login(form.value)
      router.push('/')  // navigate to home or any protected page
    } catch (err: any) {
      alert(err.message || 'Login failed')
    }
  }
  </script>

// epic_energy_front/src/app/components/login/login.component.ts
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
import { Router } from '@angular/router';

interface Response {
  token: string;
}

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})

export class LoginComponent {

  email: string = '';
  password: string = '';


  constructor(private http: HttpClient, private router: Router) { }

  login() {
    console.log('Email: ' + this.email);
    console.log('Password: ' + this.password);

    this.http.post<Response>('http://localhost:8080/api/auth/login', {
      username: this.email,
      password: this.password
    }).subscribe((response: Response) => {
      console.log('Response: ' + JSON.stringify(response));

      
      if (!response.token) {
        console.log('Login failed');
        return;
      }
      localStorage.setItem('token', response.token);
      this.router.navigate(['/dashboard']);

    });


  }
}

<div class="w-full h-screen flex justify-center items-center bg-zinc-950">
  <div class="container px-14 py-20 border rounded-md  w-2/4 bg-white">
    <form class="flex flex-col text-2xl " action="">
      <div class="form-group mb-8">
        <label for="email" class="font-semibold" >Email</label>
        <input type="email" placeholder="Insert email" class="form-control text-xl w-full bg-slate-100 my-2 p-2 border-1 border-black rounded-md focus-within:border-2" id="email" name="email" [(ngModel)]="email" required>
      </div>
      <div class="form-group mb-8">
        <label for="password" class="font-semibold">Password</label>
        <input type="password" placeholder="Insert password" class="form-control text-xl w-full bg-slate-100 my-2 p-2 border-1 border-black rounded-md focus-within:border-2" id="password" name="password" [(ngModel)]="password" required>
      </div>
      <button type="submit" class="btn btn-primary bg-yellow-400 py-2 rounded-sm hover:animate-pulse text-black text-lg font-bold" (click)="login()">LOGIN</button>
    </form>
  </div>
</div>
